name: Update AoC stats

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        env:
          AOC_SESSION: ${{ secrets.AOC2025_SESSION }}
        run: python .github/scripts/update_aoc_readme.py